version: '2'

services:

  database:
    image: mongo
    container_name: mongodb
    command: --smallfiles

  server:
    image: bsandusky/poll-server:0.3
    container_name: hapi-server
    environment:
      - MONGO_URI=mongodb://mongodb/polls
    ports:
      - "8000:8000"

  client:
    image: bsandusky/react-client:0.1
    container_name: react-client
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
